export const AUTH_USER_SUCCESSFUL = 'AUTH_USER_SUCCESS';
export const AUTH_SIGNUP_SUCCESSFUL = 'AUTH_SIGNUP_SUCCESSFUL';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const CREATE_TALK = 'CREATE_TALK';
export const ERROR_CREATE_TALK = 'ERROR_CREATE_TALK';
export const GET_ALL_TALKS = 'GET_ALL_TALKS';
export const GET_TALK_BY_ID = 'GET_TALK_BY_ID';

export const GET_ALL_USER_TALKS = 'GET_ALL_USER_TALKS';

export const DELETE_USER_TALK_BY_ID = 'DELETE_USER_TALK_BY_ID';